services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: app
        # extra_hosts:
        #     - 'host.docker.internal:host-gateway'
        volumes:
            - .:/var/www/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8084:80"
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - .:/var/www/app
        depends_on:
            - app
